### ISSUE TITLE
Storage growing continuously

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#160]
I tried to run with 4 hour retention, but disk space is growing continuously over the 4 days since I started it.

```
      containers:
      - args:
        - all
        - --storage.tsdb.path=/conprof
        - --storage.tsdb.retention.time=4h
        - --config.file=/etc/conprof/conprof.yaml
        - --http-address=:8080
        image: quay.io/conprof/conprof:master-2021-02-25-3457edb
```

This is the entire logfile; looks like it got stuck?  Scraping and UI are still working.

```
level=info ts=2021-02-26T11:20:10.847835811Z caller=repair.go:56 msg="Found healthy block" mint=1614163347593 maxt=1614297600000 ulid=01EZEBARVJ1ZAQ7FH3NT53RPJ7
level=info ts=2021-02-26T11:20:10.849056671Z caller=repair.go:56 msg="Found healthy block" mint=1614319200177 maxt=1614326400000 ulid=01EZES1X15CG6G2TYRKDYBYWFE
level=info ts=2021-02-26T11:20:10.850114138Z caller=repair.go:56 msg="Found healthy block" mint=1614326400177 maxt=1614333600000 ulid=01EZEZXM8TJ8QK54N513R3GK57
level=info ts=2021-02-26T11:20:10.851410046Z caller=repair.go:56 msg="Found healthy block" mint=1614297600177 maxt=1614319200000 ulid=01EZEZXN4BFF9YQA6DPJCRGYR1
level=info ts=2021-02-26T11:20:10.895048464Z caller=head.go:645 msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-02-26T11:20:12.532123782Z caller=head.go:659 msg="On-disk memory mappable chunks replay completed" duration=1.637044896s
level=info ts=2021-02-26T11:20:12.532162065Z caller=head.go:665 msg="Replaying WAL, this may take a while"
level=info ts=2021-02-26T11:20:12.535973672Z caller=head.go:691 msg="WAL checkpoint loaded"
level=info ts=2021-02-26T11:20:13.443256827Z caller=head.go:717 msg="WAL segment loaded" segment=65 maxSegment=68
level=info ts=2021-02-26T11:20:14.131505966Z caller=head.go:717 msg="WAL segment loaded" segment=66 maxSegment=68
level=info ts=2021-02-26T11:20:14.39420013Z caller=head.go:717 msg="WAL segment loaded" segment=67 maxSegment=68
level=info ts=2021-02-26T11:20:14.394447946Z caller=head.go:717 msg="WAL segment loaded" segment=68 maxSegment=68
level=info ts=2021-02-26T11:20:14.394472708Z caller=head.go:722 msg="WAL replay completed" checkpoint_replay_duration=3.828929ms wal_replay_duration=1.858470671s total_replay_duration=3.499393489s
level=info ts=2021-02-26T11:20:14.397532391Z caller=http.go:58 service=http/server component=all msg="listening for requests and metrics" address=:8080
2021/02/26 11:29:05 Serving web UI on  http://localhost:0
2021/02/26 11:29:10 Serving web UI on  http://localhost:0
2021/02/26 11:29:46 Serving web UI on  http://localhost:0
2021/02/26 12:52:16 Serving web UI on  http://localhost:0
2021/02/26 12:52:34 Serving web UI on  http://localhost:0
2021/02/26 12:52:43 Serving web UI on  http://localhost:0
stat /blocksconvert: no such file or directory
2021/02/26 12:52:47 Serving web UI on  http://localhost:0
2021/02/26 12:55:07 Serving web UI on  http://localhost:0
2021/02/26 12:55:16 Serving web UI on  http://localhost:0
2021/02/26 12:55:22 Serving web UI on  http://localhost:0
level=info ts=2021-02-26T13:00:02.437044897Z caller=compact.go:506 msg="write block" mint=1614333600000 maxt=1614340800000 ulid=01EZF6SCJMVQDY6YG0K0W9PH0E duration=944.120386ms
level=info ts=2021-02-26T13:00:02.444210154Z caller=head.go:824 msg="Head GC completed" duration=873.327µs
level=info ts=2021-02-26T13:00:02.506216244Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=65 to_segment=67 mint=1614340800000
level=info ts=2021-02-26T13:00:02.76080776Z caller=head.go:921 msg="WAL checkpoint complete" first=65 last=67 duration=254.726227ms
level=info ts=2021-02-26T15:00:04.335355547Z caller=compact.go:506 msg="write block" mint=1614340801478 maxt=1614348000000 ulid=01EZFDN5NQ9WFCMW42WEZVPJAF duration=952.343087ms
level=info ts=2021-02-26T15:00:04.345607506Z caller=head.go:824 msg="Head GC completed" duration=1.010266ms
level=info ts=2021-02-26T15:00:04.427835244Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=68 to_segment=69 mint=1614348000000
level=info ts=2021-02-26T15:00:04.645748315Z caller=head.go:921 msg="WAL checkpoint complete" first=68 last=69 duration=218.049752ms
level=info ts=2021-02-26T17:00:04.0260127Z caller=compact.go:506 msg="write block" mint=1614348001478 maxt=1614355200000 ulid=01EZFMGWXQP7W0T7TFECA810KX duration=642.574481ms
level=info ts=2021-02-26T17:00:04.033045337Z caller=head.go:824 msg="Head GC completed" duration=817.604µs
level=info ts=2021-02-26T17:00:04.097944143Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=70 to_segment=71 mint=1614355200000
level=info ts=2021-02-26T17:00:04.320727401Z caller=head.go:921 msg="WAL checkpoint complete" first=70 last=71 duration=222.924636ms
level=info ts=2021-02-26T17:00:12.240036867Z caller=compact.go:447 msg="compact blocks" count=3 mint=1614319200177 maxt=1614340800000 ulid=01EZFMGXV19ZVJDV1CCBZHA5M0 sources="[01EZES1X15CG6G2TYRKDYBYWFE 01EZEZXM8TJ8QK54N513R3GK57 01EZF6SCJMVQDY6YG0K0W9PH0E]" duration=7.919002189s
level=info ts=2021-02-26T17:00:12.284015895Z caller=db.go:1189 msg="Deleting obsolete block" block=01EZF6SCJMVQDY6YG0K0W9PH0E
level=info ts=2021-02-26T17:00:12.31475957Z caller=db.go:1189 msg="Deleting obsolete block" block=01EZES1X15CG6G2TYRKDYBYWFE
level=info ts=2021-02-26T17:00:12.342587672Z caller=db.go:1189 msg="Deleting obsolete block" block=01EZEZXM8TJ8QK54N513R3GK57
2021/02/26 17:20:18 Serving web UI on  http://localhost:0
level=info ts=2021-02-26T19:00:04.562363712Z caller=compact.go:506 msg="write block" mint=1614355201478 maxt=1614362400000 ulid=01EZFVCM5QP139FV65F10F2709 duration=1.179309374s
level=info ts=2021-02-26T19:00:04.571055029Z caller=head.go:824 msg="Head GC completed" duration=1.029109ms
level=info ts=2021-02-26T19:00:04.640246921Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=72 to_segment=73 mint=1614362400000
level=info ts=2021-02-26T19:00:04.886541637Z caller=head.go:921 msg="WAL checkpoint complete" first=72 last=73 duration=246.432558ms
level=info ts=2021-02-26T21:00:06.244124985Z caller=compact.go:506 msg="write block" mint=1614362401478 maxt=1614369600000 ulid=01EZG28BDQQZ32GK80V68SFEPW duration=2.860323305s
level=info ts=2021-02-26T21:00:06.252746555Z caller=head.go:824 msg="Head GC completed" duration=872.273µs
level=info ts=2021-02-26T21:00:06.29288143Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=74 to_segment=75 mint=1614369600000
level=info ts=2021-02-26T21:00:06.527013328Z caller=head.go:921 msg="WAL checkpoint complete" first=74 last=75 duration=234.275547ms
level=info ts=2021-02-26T23:00:02.238456384Z caller=compact.go:506 msg="write block" mint=1614369601117 maxt=1614376800000 ulid=01EZG940TN35QRGSXXAFCMDGJ3 duration=745.328747ms
level=info ts=2021-02-26T23:00:02.246877818Z caller=head.go:824 msg="Head GC completed" duration=845.64µs
level=info ts=2021-02-26T23:00:02.337550991Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=76 to_segment=77 mint=1614376800000
level=info ts=2021-02-26T23:00:02.564973884Z caller=head.go:921 msg="WAL checkpoint complete" first=76 last=77 duration=227.610707ms
level=info ts=2021-02-26T23:00:04.89628212Z caller=compact.go:447 msg="compact blocks" count=3 mint=1614340801478 maxt=1614362400000 ulid=01EZG941W5PTWXWKVTJT5M2FZB sources="[01EZFDN5NQ9WFCMW42WEZVPJAF 01EZFMGWXQP7W0T7TFECA810KX 01EZFVCM5QP139FV65F10F2709]" duration=2.330881761s
```

Goroutine profile https://share.polarsignals.com/5ea1195/

(excerpt:
```
goroutine 55 [semacquire, 3776 minutes]:
sync.runtime_Semacquire(0xc00044191c)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00044191c)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/conprof/db/tsdb.(*Block).Close(0xc000441900, 0xc0015b3620, 0xc0015b32e8)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/block.go:326 +0x6f
github.com/conprof/db/tsdb.(*DB).deleteBlocks(0xc000150460, 0xc0015b3620, 0xc0015b346e, 0x41c3b80)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:1168 +0x7c5
github.com/conprof/db/tsdb.(*DB).reloadBlocks(0xc000150460, 0x0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:1043 +0x11e5
github.com/conprof/db/tsdb.(*DB).compactBlocks(0xc000150460, 0x177e05b0f00, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:912 +0x188
github.com/conprof/db/tsdb.(*DB).Compact(0xc000150460, 0x0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:844 +0x40a
github.com/conprof/db/tsdb.(*DB).run(0xc000150460)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:747 +0x27e
created by github.com/conprof/db/tsdb.open
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:686 +0x791
```

**Comment by brancz** [comment]
That's very curious, thank you for reporting! We will need to investigate a bit.

**Comment by brancz** [comment]
I think I found something. We were passing the durations as nanoseconds instead of the expected milliseconds. PR incoming to fix.

**Comment by bboreham** [comment]
Thanks!  Storage came down from 26GB to 4GB a few minutes after deploying that version.
However memory usage went up to 11GB which was uncomfortable for the machine it was running on.
(Go heap stayed around 100MB)

**Comment by brancz** [comment]
hmm that's odd, are you saying it might not have run GC? Perhaps it was mmap?

**Comment by bboreham** [comment]
Memory went down to 5GB after the storage cleared out.

![image](https://user-images.githubusercontent.com/8125524/109661979-754e2880-7b62-11eb-9bbf-a3f1bd54dd39.png)

I'm not saying anything about what caused it, just passing on the observation.

**Comment by brancz** [comment]
What is the "memory_usage" metric displayed here since it's not RSS? working-set-bytes?

**Comment by bboreham** [comment]
`container_memory_usage_bytes`

**Comment by bboreham** [comment]
Happened again, this time with `quay.io/conprof/conprof:master-2021-03-01-f8fd707`

tail of log:

```
...
level=info ts=2021-03-13T13:00:07.557368335Z caller=compact.go:506 msg="write block" mint=1615629601836 maxt=1615636800000 ulid=01F0NTR8T8SMWMCTMX8G9E0CE6 duration=2.748419297s
level=info ts=2021-03-13T13:00:07.564672353Z caller=head.go:824 msg="Head GC completed" duration=892.86µs
level=info ts=2021-03-13T13:00:07.729770362Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=136 to_segment=142 mint=1615636800000
level=info ts=2021-03-13T13:00:08.472252419Z caller=head.go:921 msg="WAL checkpoint complete" first=136 last=142 duration=742.669385ms
2021/03/13 13:58:10 Serving web UI on  http://localhost:0
2021/03/13 13:58:15 Serving web UI on  http://localhost:0
2021/03/13 14:04:41 Serving web UI on  http://localhost:0
stat /bin/cortex: no such file or directory
2021/03/13 14:08:13 Serving web UI on  http://localhost:0
2021/03/13 14:08:25 Serving web UI on  http://localhost:0
2021/03/13 14:08:32 Serving web UI on  http://localhost:0
2021/03/13 14:13:52 Serving web UI on  http://localhost:0
stat /bin/cortex: no such file or directory
2021/03/13 14:34:25 Serving web UI on  http://localhost:0
stat /bin/cortex: no such file or directory
2021/03/13 14:34:28 Serving web UI on  http://localhost:0
level=info ts=2021-03-13T15:00:07.577403797Z caller=compact.go:506 msg="write block" mint=1615636801836 maxt=1615644000000 ulid=01F0P1M02D70TJE1X414SDEW2X duration=2.763691121s
level=info ts=2021-03-13T15:00:07.585751996Z caller=head.go:824 msg="Head GC completed" duration=1.004223ms
level=info ts=2021-03-13T15:00:07.784251426Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=143 to_segment=149 mint=1615644000000
level=info ts=2021-03-13T15:00:08.557694235Z caller=head.go:921 msg="WAL checkpoint complete" first=143 last=149 duration=779.295134ms
level=info ts=2021-03-13T17:00:04.698770239Z caller=compact.go:506 msg="write block" mint=1615644001836 maxt=1615651200000 ulid=01F0P8FME6J8EFPBJ9BYG6GH40 duration=2.836520632s
level=info ts=2021-03-13T17:00:04.719662063Z caller=db.go:1189 msg="Deleting obsolete block" block=01F0H24J92REY5KG6VK51CA2ES
level=info ts=2021-03-13T17:00:04.720942207Z caller=head.go:824 msg="Head GC completed" duration=1.164577ms
level=info ts=2021-03-13T17:00:04.924226088Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=150 to_segment=156 mint=1615651200000
level=info ts=2021-03-13T17:00:05.848338804Z caller=head.go:921 msg="WAL checkpoint complete" first=150 last=156 duration=924.318286ms
level=info ts=2021-03-13T19:00:07.696301104Z caller=compact.go:506 msg="write block" mint=1615651201836 maxt=1615658400000 ulid=01F0PFBEJ8GKVXYE6G6VERDN8P duration=2.887883351s
2021/03/14 14:05:49 Serving web UI on  http://localhost:0
2021/03/14 14:05:53 Serving web UI on  http://localhost:0
```

**Comment by bboreham** [comment]
I guess #182 may give some hints as to why memory usage went way up, if it's memory-mapping every segment before starting to  discard old data.

Also my comment about the Go heap must be mistaken, since conprof isn't serving metrics until after WAL replay (#37).
