### ISSUE TITLE
Panic while running UnmarshalYAMLWithInlineConfigs()

### ISSUE THREAD

**Issue by dgzlopes** [conprof/conprof#93]
Found the following panic while trying to run the project locally.

## Context information (for bug reports)
**Output of `go version`**
```
➜  go version  
go version go1.13.8 linux/amd64
```

## Steps to reproduce the issue
Run the [quickstart](https://github.com/conprof/conprof#quickstart):
```
➜ git clone git@github.com:conprof/conprof.git
➜ GO111MODULE=on GOPROXY=https://proxy.golang.org go install -v
➜ conprof all --config.file examples/conprof.yaml --web.listen-address 0.0.0.0:10902 --storage.tsdb.path ./data
```
The error appears too if you run `make test` (github.com/conprof/conprof/config).
### Observations
Researched the error a bit, and it starts appearing after #73.

### Stacktrace / full error message

```
level=info ts=2020-10-13T19:36:54.660385024Z caller=head.go:648 msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2020-10-13T19:36:54.660454504Z caller=head.go:662 msg="On-disk memory mappable chunks replay completed" duration=2.54µs
level=info ts=2020-10-13T19:36:54.660471325Z caller=head.go:668 msg="Replaying WAL, this may take a while"
level=info ts=2020-10-13T19:36:54.66093177Z caller=head.go:720 msg="WAL segment loaded" segment=0 maxSegment=32
level=info ts=2020-10-13T19:36:54.661276244Z caller=head.go:720 msg="WAL segment loaded" segment=1 maxSegment=32
level=info ts=2020-10-13T19:36:54.661857341Z caller=head.go:720 msg="WAL segment loaded" segment=2 maxSegment=32
level=info ts=2020-10-13T19:36:54.662097643Z caller=head.go:720 msg="WAL segment loaded" segment=3 maxSegment=32
level=info ts=2020-10-13T19:36:54.664607202Z caller=head.go:720 msg="WAL segment loaded" segment=4 maxSegment=32
level=info ts=2020-10-13T19:36:54.664955677Z caller=head.go:720 msg="WAL segment loaded" segment=5 maxSegment=32
level=info ts=2020-10-13T19:36:54.665107558Z caller=head.go:720 msg="WAL segment loaded" segment=6 maxSegment=32
level=info ts=2020-10-13T19:36:54.665204339Z caller=head.go:720 msg="WAL segment loaded" segment=7 maxSegment=32
level=info ts=2020-10-13T19:36:54.66526041Z caller=head.go:720 msg="WAL segment loaded" segment=8 maxSegment=32
level=info ts=2020-10-13T19:36:54.665333451Z caller=head.go:720 msg="WAL segment loaded" segment=9 maxSegment=32
level=info ts=2020-10-13T19:36:54.665408112Z caller=head.go:720 msg="WAL segment loaded" segment=10 maxSegment=32
level=info ts=2020-10-13T19:36:54.665473143Z caller=head.go:720 msg="WAL segment loaded" segment=11 maxSegment=32
level=info ts=2020-10-13T19:36:54.665548043Z caller=head.go:720 msg="WAL segment loaded" segment=12 maxSegment=32
level=info ts=2020-10-13T19:36:54.665618744Z caller=head.go:720 msg="WAL segment loaded" segment=13 maxSegment=32
level=info ts=2020-10-13T19:36:54.665693005Z caller=head.go:720 msg="WAL segment loaded" segment=14 maxSegment=32
level=info ts=2020-10-13T19:36:54.665773756Z caller=head.go:720 msg="WAL segment loaded" segment=15 maxSegment=32
level=info ts=2020-10-13T19:36:54.668818861Z caller=head.go:720 msg="WAL segment loaded" segment=16 maxSegment=32
level=info ts=2020-10-13T19:36:54.669494709Z caller=head.go:720 msg="WAL segment loaded" segment=17 maxSegment=32
level=info ts=2020-10-13T19:36:54.669672471Z caller=head.go:720 msg="WAL segment loaded" segment=18 maxSegment=32
level=info ts=2020-10-13T19:36:54.670020305Z caller=head.go:720 msg="WAL segment loaded" segment=19 maxSegment=32
level=info ts=2020-10-13T19:36:54.670192557Z caller=head.go:720 msg="WAL segment loaded" segment=20 maxSegment=32
level=info ts=2020-10-13T19:36:54.67044766Z caller=head.go:720 msg="WAL segment loaded" segment=21 maxSegment=32
level=info ts=2020-10-13T19:36:54.670698213Z caller=head.go:720 msg="WAL segment loaded" segment=22 maxSegment=32
level=info ts=2020-10-13T19:36:54.670933656Z caller=head.go:720 msg="WAL segment loaded" segment=23 maxSegment=32
level=info ts=2020-10-13T19:36:54.671190889Z caller=head.go:720 msg="WAL segment loaded" segment=24 maxSegment=32
level=info ts=2020-10-13T19:36:54.671472342Z caller=head.go:720 msg="WAL segment loaded" segment=25 maxSegment=32
level=info ts=2020-10-13T19:36:54.671965558Z caller=head.go:720 msg="WAL segment loaded" segment=26 maxSegment=32
level=info ts=2020-10-13T19:36:54.672251951Z caller=head.go:720 msg="WAL segment loaded" segment=27 maxSegment=32
level=info ts=2020-10-13T19:36:54.672640416Z caller=head.go:720 msg="WAL segment loaded" segment=28 maxSegment=32
level=info ts=2020-10-13T19:36:54.673203792Z caller=head.go:720 msg="WAL segment loaded" segment=29 maxSegment=32
level=info ts=2020-10-13T19:36:54.673518056Z caller=head.go:720 msg="WAL segment loaded" segment=30 maxSegment=32
level=info ts=2020-10-13T19:36:54.67387757Z caller=head.go:720 msg="WAL segment loaded" segment=31 maxSegment=32
level=info ts=2020-10-13T19:36:54.674372576Z caller=head.go:720 msg="WAL segment loaded" segment=32 maxSegment=32
level=info ts=2020-10-13T19:36:54.674400986Z caller=head.go:725 msg="WAL replay completed" checkpoint_replay_duration=118.471µs wal_replay_duration=13.79712ms total_replay_duration=13.945822ms
panic: reflect.StructOf: StructOf does not allow unexported fields [recovered]
        panic: reflect.StructOf: StructOf does not allow unexported fields

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc0011a38b0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/yaml.go:249 +0x9a
panic(0x2179c80, 0x2d3e970)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
reflect.runtimeStructField(0xc0001e2660, 0x18, 0x202f4e3, 0x21, 0x2e363e0, 0x229c260, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.13/src/reflect/type.go:2754 +0x1c1
reflect.StructOf(0xc000a47000, 0x1a, 0x27, 0x0, 0x0)
        /usr/lib/go-1.13/src/reflect/type.go:2362 +0x2356
github.com/prometheus/prometheus/discovery.getConfigType(0x2e363e0, 0x2628ba0, 0x0, 0x0)
        /home/dgzlopes/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200922180708-b0145884d381/discovery/registry.go:105 +0x6ea
github.com/prometheus/prometheus/discovery.UnmarshalYAMLWithInlineConfigs(0x232d180, 0xc0002320f0, 0xc00018c1a0, 0xdf8475800, 0xdf8475800)
        /home/dgzlopes/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200922180708-b0145884d381/discovery/registry.go:125 +0x1ba
github.com/conprof/conprof/config.(*ScrapeConfig).UnmarshalYAML(0xc0002320f0, 0xc00018c1a0, 0x4107af0, 0x0)
        /home/dgzlopes/conprof/config/config.go:190 +0x93
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0xc000b30120, 0xc0003890a0, 0x7f2e11e9d520, 0xc0002320f0, 0xc0002320f0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:270 +0xac
gopkg.in/yaml%2ev2.(*decoder).prepare(0xc000b30120, 0xc0003890a0, 0x232d180, 0xc0006600e8, 0x196, 0x8, 0x232d180, 0xc00018c101, 0xc0006600e8)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:313 +0x197
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000b30120, 0xc0003890a0, 0x232d180, 0xc0006600e8, 0x196, 0x196)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:364 +0xe3
gopkg.in/yaml%2ev2.(*decoder).sequence(0xc000b30120, 0xc000389030, 0x210aae0, 0xc00018c020, 0x197, 0x210aae0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:609 +0x25c
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000b30120, 0xc000389030, 0x210aae0, 0xc00018c020, 0x197, 0xc00018c020)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:374 +0x183
gopkg.in/yaml%2ev2.(*decoder).mappingStruct(0xc000b30120, 0xc00036dab0, 0x2387fa0, 0xc00018c020, 0x199, 0x1fa0ff6)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:767 +0xa6c
gopkg.in/yaml%2ev2.(*decoder).mapping(0xc000b30120, 0xc00036dab0, 0x2387fa0, 0xc00018c020, 0x199, 0x2387fa0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:626 +0xa94
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000b30120, 0xc00036dab0, 0x2387fa0, 0xc00018c020, 0x199, 0x0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:372 +0x1af
gopkg.in/yaml%2ev2.(*decoder).document(0xc000b30120, 0xc00036d6c0, 0x2387fa0, 0xc00018c020, 0x199, 0xa0ed50)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:384 +0x7c
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000b30120, 0xc00036d6c0, 0x2387fa0, 0xc00018c020, 0x199, 0x199)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/decode.go:360 +0x247
gopkg.in/yaml%2ev2.unmarshal(0xc000222990, 0x83, 0x90, 0x22b26e0, 0xc00018c020, 0x1, 0x0, 0x0)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/yaml.go:148 +0x35d
gopkg.in/yaml%2ev2.UnmarshalStrict(...)
        /home/dgzlopes/go/pkg/mod/gopkg.in/yaml.v2@v2.3.0/yaml.go:89
github.com/conprof/conprof/config.Load(0xc0002223f0, 0x83, 0x83, 0x283, 0xc0002223f0)
        /home/dgzlopes/conprof/config/config.go:116 +0x99
github.com/conprof/conprof/config.LoadFile(0x7ffe20552d9a, 0x15, 0xc000050300, 0x2, 0x2)
        /home/dgzlopes/conprof/config/config.go:130 +0xa4
main.runSampler(0xc00052fe80, 0x2d92160, 0xc0007e8090, 0xc0002ce000, 0x7ffe20552d9a, 0x15, 0xc000050240, 0xc0002ce000, 0x0)
        /home/dgzlopes/conprof/sampler.go:100 +0x20f
main.runAll(0xc00052fe80, 0xc00043a3c0, 0x2d92160, 0xc0007e8090, 0x7ffe20552de7, 0x6, 0x7ffe20552d9a, 0x15, 0x49ab483a10000, 0xc000050240, ...)
        /home/dgzlopes/conprof/all.go:71 +0x12b
main.registerAll.func1(0xc00052fe80, 0xc00043a3c0, 0x2d92160, 0xc0007e8090, 0xc0007fc000, 0x0, 0x0, 0x0, 0x2dfffa0, 0x2dfffa0)
        /home/dgzlopes/conprof/all.go:40 +0x92
main.main()
        /home/dgzlopes/conprof/main.go:119 +0xe88
```

**Comment by dgzlopes** [comment]
Had a dev-env dep issue. It's fixed. 

Closing!
